import type { Express } from "express";
import { Server } from "http";
import { storage } from "./storage";
import {
  insertClientSchema, insertIncomeSchema, insertExpenseSchema,
  insertMealSchema, insertMileageSchema
} from "@shared/schema";
import { z } from "zod";
import nodemailer from "nodemailer";

const BOOKKEEPER_EMAIL = "d.d.boutte@theltdgroupllc.com";
const IRS_MILEAGE_RATE = 0.70; // 2025 rate

const MONTH_NAMES = [
  "January","February","March","April","May","June",
  "July","August","September","October","November","December"
];

function formatCurrency(n: number) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(n);
}

function buildSummaryEmailHtml(client: any, summary: any, month: number, year: number) {
  const monthName = MONTH_NAMES[month - 1];
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <style>
    body { font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
    h1 { color: #1a5276; border-bottom: 2px solid #1a5276; padding-bottom: 10px; }
    h2 { color: #2874a6; margin-top: 24px; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; }
    th { background: #1a5276; color: white; padding: 8px 12px; text-align: left; }
    td { padding: 7px 12px; border-bottom: 1px solid #ddd; }
    tr:nth-child(even) { background: #f4f6f9; }
    .summary-box { background: #eaf4fb; border: 1px solid #aed6f1; border-radius: 8px; padding: 16px 20px; margin-top: 20px; }
    .summary-row { display: flex; justify-content: space-between; padding: 4px 0; }
    .total-row { font-weight: bold; font-size: 1.1em; border-top: 2px solid #1a5276; margin-top: 8px; padding-top: 8px; }
    .profit-positive { color: #1e8449; font-weight: bold; }
    .profit-negative { color: #c0392b; font-weight: bold; }
    .footer { font-size: 0.8em; color: #888; margin-top: 30px; border-top: 1px solid #ddd; padding-top: 10px; }
    .label { color: #666; }
  </style>
</head>
<body>
  <h1>Monthly Business Summary</h1>
  <p><strong>${monthName} ${year}</strong></p>
  <p>
    <strong>Client:</strong> ${client.name}<br/>
    <strong>Business:</strong> ${client.businessName}<br/>
    <strong>Email:</strong> ${client.email}${client.phone ? `<br/><strong>Phone:</strong> ${client.phone}` : ""}
  </p>

  <div class="summary-box">
    <h2 style="margin-top:0">Financial Overview</h2>
    <div class="summary-row"><span class="label">Total Income</span><span class="profit-positive">${formatCurrency(summary.totalIncome)}</span></div>
    <div class="summary-row"><span class="label">Total Business Expenses</span><span>${formatCurrency(summary.totalExpenses)}</span></div>
    <div class="summary-row"><span class="label">Meal Expenses (actual)</span><span>${formatCurrency(summary.totalMeals)}</span></div>
    <div class="summary-row"><span class="label">Meal Deduction (50%)</span><span>${formatCurrency(summary.totalMealDeductible)}</span></div>
    <div class="summary-row"><span class="label">Miles Driven</span><span>${summary.totalMiles.toFixed(1)} mi</span></div>
    <div class="summary-row"><span class="label">Mileage Deduction (@$${IRS_MILEAGE_RATE}/mi)</span><span>${formatCurrency(summary.totalMileageDeductible)}</span></div>
    <div class="summary-row total-row">
      <span>Total Deductible Expenses</span>
      <span>${formatCurrency(summary.totalExpenses + summary.totalMealDeductible + summary.totalMileageDeductible)}</span>
    </div>
    <div class="summary-row total-row">
      <span>Net Profit</span>
      <span class="${summary.netProfit >= 0 ? "profit-positive" : "profit-negative"}">${formatCurrency(summary.netProfit)}</span>
    </div>
  </div>

  <div class="footer">
    <p>This summary was automatically generated by the LTD Group Business Tracker for ${client.businessName}.</p>
    <p>For questions, contact the client at ${client.email}.</p>
  </div>
</body>
</html>
  `;
}

export function registerRoutes(httpServer: Server, app: Express) {
  // ---- CLIENTS ----
  app.get("/api/clients", (_req, res) => {
    res.json(storage.getClients());
  });

  app.get("/api/clients/:id", (req, res) => {
    const client = storage.getClient(Number(req.params.id));
    if (!client) return res.status(404).json({ error: "Not found" });
    res.json(client);
  });

  app.post("/api/clients", (req, res) => {
    const parsed = insertClientSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues });
    const client = storage.createClient(parsed.data);
    res.json(client);
  });

  app.patch("/api/clients/:id", (req, res) => {
    const client = storage.updateClient(Number(req.params.id), req.body);
    if (!client) return res.status(404).json({ error: "Not found" });
    res.json(client);
  });

  app.delete("/api/clients/:id", (req, res) => {
    storage.deleteClient(Number(req.params.id));
    res.json({ success: true });
  });

  // ---- INCOME ----
  app.get("/api/clients/:clientId/income", (req, res) => {
    const { month, year } = req.query;
    const entries = storage.getIncome(
      Number(req.params.clientId),
      month ? Number(month) : undefined,
      year ? Number(year) : undefined
    );
    res.json(entries);
  });

  app.post("/api/clients/:clientId/income", (req, res) => {
    const body = { ...req.body, clientId: Number(req.params.clientId) };
    const parsed = insertIncomeSchema.safeParse(body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues });
    const entry = storage.createIncome(parsed.data);
    res.json(entry);
  });

  app.delete("/api/income/:id", (req, res) => {
    storage.deleteIncome(Number(req.params.id));
    res.json({ success: true });
  });

  // ---- EXPENSES ----
  app.get("/api/clients/:clientId/expenses", (req, res) => {
    const { month, year } = req.query;
    const entries = storage.getExpenses(
      Number(req.params.clientId),
      month ? Number(month) : undefined,
      year ? Number(year) : undefined
    );
    res.json(entries);
  });

  app.post("/api/clients/:clientId/expenses", (req, res) => {
    const body = { ...req.body, clientId: Number(req.params.clientId) };
    const parsed = insertExpenseSchema.safeParse(body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues });
    const entry = storage.createExpense(parsed.data);
    res.json(entry);
  });

  app.delete("/api/expenses/:id", (req, res) => {
    storage.deleteExpense(Number(req.params.id));
    res.json({ success: true });
  });

  // ---- MEALS ----
  app.get("/api/clients/:clientId/meals", (req, res) => {
    const { month, year } = req.query;
    const entries = storage.getMeals(
      Number(req.params.clientId),
      month ? Number(month) : undefined,
      year ? Number(year) : undefined
    );
    res.json(entries);
  });

  app.post("/api/clients/:clientId/meals", (req, res) => {
    const amount = Number(req.body.amount);
    const body = {
      ...req.body,
      clientId: Number(req.params.clientId),
      amount,
      deductibleAmount: Math.round(amount * 0.5 * 100) / 100,
    };
    const parsed = insertMealSchema.safeParse(body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues });
    const entry = storage.createMeal(parsed.data);
    res.json(entry);
  });

  app.delete("/api/meals/:id", (req, res) => {
    storage.deleteMeal(Number(req.params.id));
    res.json({ success: true });
  });

  // ---- MILEAGE ----
  app.get("/api/clients/:clientId/mileage", (req, res) => {
    const { month, year } = req.query;
    const entries = storage.getMileage(
      Number(req.params.clientId),
      month ? Number(month) : undefined,
      year ? Number(year) : undefined
    );
    res.json(entries);
  });

  app.post("/api/clients/:clientId/mileage", (req, res) => {
    const miles = Number(req.body.miles);
    const body = {
      ...req.body,
      clientId: Number(req.params.clientId),
      miles,
      irsRate: IRS_MILEAGE_RATE,
      deductibleAmount: Math.round(miles * IRS_MILEAGE_RATE * 100) / 100,
    };
    const parsed = insertMileageSchema.safeParse(body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues });
    const entry = storage.createMileage(parsed.data);
    res.json(entry);
  });

  app.delete("/api/mileage/:id", (req, res) => {
    storage.deleteMileage(Number(req.params.id));
    res.json({ success: true });
  });

  // ---- MONTHLY SUMMARY ----
  app.get("/api/clients/:clientId/summaries", (req, res) => {
    res.json(storage.getSummaries(Number(req.params.clientId)));
  });

  app.get("/api/clients/:clientId/summary/:year/:month", (req, res) => {
    const { clientId, year, month } = req.params;
    const summary = storage.getMonthlySummary(Number(clientId), Number(month), Number(year));
    res.json(summary || null);
  });

  // Generate / refresh summary for a month
  app.post("/api/clients/:clientId/summary/:year/:month/generate", (req, res) => {
    const clientId = Number(req.params.clientId);
    const month = Number(req.params.month);
    const year = Number(req.params.year);

    const income = storage.getIncome(clientId, month, year);
    const expenses = storage.getExpenses(clientId, month, year);
    const meals = storage.getMeals(clientId, month, year);
    const mileage = storage.getMileage(clientId, month, year);

    const totalIncome = income.reduce((s, r) => s + r.amount, 0);
    const totalExpenses = expenses.reduce((s, r) => s + r.amount, 0);
    const totalMeals = meals.reduce((s, r) => s + r.amount, 0);
    const totalMealDeductible = meals.reduce((s, r) => s + r.deductibleAmount, 0);
    const totalMiles = mileage.reduce((s, r) => s + r.miles, 0);
    const totalMileageDeductible = mileage.reduce((s, r) => s + r.deductibleAmount, 0);
    const netProfit = totalIncome - totalExpenses - totalMealDeductible - totalMileageDeductible;

    const summary = storage.upsertMonthlySummary({
      clientId,
      month,
      year,
      totalIncome,
      totalExpenses,
      totalMeals,
      totalMealDeductible,
      totalMiles,
      totalMileageDeductible,
      netProfit,
      sentToBookkeeper: false,
      sentAt: null,
    });
    res.json(summary);
  });

  // Send summary to bookkeeper via email
  app.post("/api/clients/:clientId/summary/:year/:month/send", async (req, res) => {
    const clientId = Number(req.params.clientId);
    const month = Number(req.params.month);
    const year = Number(req.params.year);

    const client = storage.getClient(clientId);
    if (!client) return res.status(404).json({ error: "Client not found" });

    let summary = storage.getMonthlySummary(clientId, month, year);
    if (!summary) {
      // Auto-generate if needed
      const income = storage.getIncome(clientId, month, year);
      const expenses = storage.getExpenses(clientId, month, year);
      const meals = storage.getMeals(clientId, month, year);
      const mileage = storage.getMileage(clientId, month, year);
      const totalIncome = income.reduce((s, r) => s + r.amount, 0);
      const totalExpenses = expenses.reduce((s, r) => s + r.amount, 0);
      const totalMeals = meals.reduce((s, r) => s + r.amount, 0);
      const totalMealDeductible = meals.reduce((s, r) => s + r.deductibleAmount, 0);
      const totalMiles = mileage.reduce((s, r) => s + r.miles, 0);
      const totalMileageDeductible = mileage.reduce((s, r) => s + r.deductibleAmount, 0);
      const netProfit = totalIncome - totalExpenses - totalMealDeductible - totalMileageDeductible;
      summary = storage.upsertMonthlySummary({
        clientId, month, year, totalIncome, totalExpenses, totalMeals,
        totalMealDeductible, totalMiles, totalMileageDeductible, netProfit,
        sentToBookkeeper: false, sentAt: null,
      });
    }

    const monthName = MONTH_NAMES[month - 1];
    const htmlBody = buildSummaryEmailHtml(client, summary, month, year);

    // Build plain text version
    const textBody = `
Monthly Business Summary – ${monthName} ${year}

Client: ${client.name}
Business: ${client.businessName}
Email: ${client.email}

FINANCIAL OVERVIEW
==================
Total Income:               ${formatCurrency(summary.totalIncome)}
Total Business Expenses:    ${formatCurrency(summary.totalExpenses)}
Meal Expenses (actual):     ${formatCurrency(summary.totalMeals)}
Meal Deduction (50%):       ${formatCurrency(summary.totalMealDeductible)}
Miles Driven:               ${summary.totalMiles.toFixed(1)} mi
Mileage Deduction:          ${formatCurrency(summary.totalMileageDeductible)}
Total Deductible Expenses:  ${formatCurrency(summary.totalExpenses + summary.totalMealDeductible + summary.totalMileageDeductible)}
Net Profit:                 ${formatCurrency(summary.netProfit)}

Generated by LTD Group Business Tracker.
    `.trim();

    try {
      // Use Gmail SMTP with app password if env vars are set, otherwise log to console
      const bookkeeperEmail = client.bookkeeperEmail || BOOKKEEPER_EMAIL;

      if (process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASS) {
        const transporter = nodemailer.createTransport({
          host: process.env.SMTP_HOST,
          port: Number(process.env.SMTP_PORT) || 587,
          secure: false,
          auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS },
        });
        await transporter.sendMail({
          from: `"LTD Group Tracker" <${process.env.SMTP_USER}>`,
          to: bookkeeperEmail,
          subject: `📊 Monthly Summary: ${client.businessName} – ${monthName} ${year}`,
          text: textBody,
          html: htmlBody,
        });
      } else {
        // Log to console when SMTP not configured (demo mode)
        console.log("\n====== EMAIL TO BOOKKEEPER ======");
        console.log(`TO: ${bookkeeperEmail}`);
        console.log(`SUBJECT: Monthly Summary: ${client.businessName} – ${monthName} ${year}`);
        console.log(textBody);
        console.log("=================================\n");
      }

      const updated = storage.markSummarySent(summary.id);
      res.json({ success: true, summary: updated, emailSentTo: bookkeeperEmail });
    } catch (err: any) {
      console.error("Email error:", err);
      res.status(500).json({ error: "Failed to send email: " + err.message });
    }
  });
}
